enable:
  issues: false
  prs: true

labels:
  "bug":
    include:
      - '\[.*\bbug\b.*\]'
    exclude: []
  "help wanted":
    include:
      - '\[.*\bhelp( me)?\b.*\]'
    exclude:
      - '\[.*\btest(ing)?\b.*\]'
  "enhancement":
    include:
      - '\[.*\bfeat\b.*\]'
    exclude: []
