enable:
  issues: false
  prs: true

labels:
  "bug":
    include:
      - 'bug[s]?\b:'
    exclude: []
  "help wanted":
    include:
      - 'help( me)?\b:'
    exclude:
      - 'test(ing)?\b:'
  "enhancement":
    include:
      - 'feat\b:'
    exclude: []
