enable:
  issues: false
  prs: true

labels:
  "bug":
    include:
      - '\[.*bug.*\]'
    exclude: []
  "help wanted":
    include:
      - '\[.*help( me)?.*\]'
    exclude:
      - '\[.*test(ing)?.*\]'
  "enhancement":
    include:
      - '\[.*feat.*\]'
    exclude: []
