name: Manage Reviewers on PR Opened

on:
  pull_request:
    types: [opened]

permissions: write-all

jobs:
  manage_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set assignee to github.actor
        id: add_assignee
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const assignee = context.actor;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: prNumber,
              assignees: [assignee]
            });

      - name: Set reviewers if none are set
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const assignee = context.payload.pull_request.assignees[0].login;
            const prNumber = context.payload.pull_request.number;

            const { data: reviewersData } = await github.rest.pulls.listRequestedReviewers({
              owner,
              repo,
              pull_number: prNumber
            });


            const reviewers = reviewersData.users.map(user => user.login);
            const teamReviewers = reviewersData.teams.map(team => team.name);

            console.log('Reviewers:', reviewers);
            console.log('Team Reviewers:', teamReviewers);

            if (reviewers.length > 0 || teamReviewers.length > 0) {
              return;
            }

            let reviewersToSet = [];

            if (assignee === 'shorrykim') {
              console.log('hihi1');
              reviewersToSet = ['HyosikPark', 'jiwoong-im', 'taerikor'];
            } else if (assignee === 'HyosikPark') {
              console.log('hihi2');
              reviewersToSet = ['shorrykim', 'jiwoong-im', 'taerikor'];
            } else if (assignee === 'jiwoong-im') {
              console.log('hihi3');
              reviewersToSet = ['HyosikPark', 'shorrykim', 'taerikor'];
            } else if (assignee === 'taerikor') {
              console.log('hihi4');
              reviewersToSet = ['HyosikPark', 'jiwoong-im', 'shorrykim'];
            }

            console.log('Reviewers to set:', reviewersToSet);
            if (reviewersToSet.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: prNumber,
                reviewers: reviewersToSet
              });
            }
