name: Auto Asignee

on:
  pull_request:
    types: [opened]

permissions: read-all

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{ github.actor }}
